### ISSUE TITLE
Should `sync` work both ways with `State` objects?

### ISSUE THREAD

**Issue by TodePond** [TodePond/HyperTode#3]
```js
const name = new State("Enter your name here...")
const input = document.createElement("input")
sync(input, "value", name)
```

What should happen when the user changes `input.value` by typing into the input?
Currently it does nothing, which causes the input to get out of sync. But maybe it's too much to hijack it in the reverse.

What about introducing another function that syncs both ways?
```js
const name = new State("Enter your name here...")
const input = document.createElement("input")
bind(input, "value", name)
```

Not sure it's a good idea to introduce another function.
If I do, the naming of `sync` would need to change to better represent that it DOESN'T sync both ways I think.

**Comment by TodePond** [comment]
No! Keep it simple

**Comment by Magnogen** [comment]
I agree with you, naming it `sync` would imply that the two values will always remain the same as each other; if one changes, so does the other.

Bear in mind that, if implemented poorly, an infinite loop can easily happen in this scenario - and the same applies to two individual functions as well.

If you wanted to give them separate names, what about `listen` (for updating a state from an event) and `update` (for updating the DOM when the state changes)?

I'm loving how this is coming along, as well as how simple you're making it!

**Comment by TodePond** [comment]
Yeah `sync` sounds like both ways, doesn't it.

I think I won't do the 'auto-update' the state from an event (similar to `bind` in svelte) because that feels a bit less simple to me.
But there could be a better name for what `sync` currently does 🤔

**Comment by Magnogen** [comment]
`link`? Making it like they're joined together?

`entangle`? A bit of a longer name, but it comes from Quantum Entanglement - really similar.

`couple`? Like coupling a trailer to a car?

`graft` could also work, it's a horticultural term for when someone attaches two types of tree together. Idk I'm spit balling now.

I quite like `entangle` tbh as it fits the description well, but I can understand if you don't for it - it's quite long hah.
