### ISSUE TITLE
Change `sync` to `subscribe`

### ISSUE THREAD

**Issue by TodePond** [TodePond/HyperTode#5]
`sync` implies it's both-ways but it's just one-way

**Comment by TodePond** [comment]
```js
listen(object, propertyName, state)
```

The word 'listen' is already taken by event listeners though?

```js
follow(object, propertyName, state)
```

**Comment by TodePond** [comment]
`imitate`?

**Comment by TodePond** [comment]
more ideas in #3

**Comment by Magnogen** [comment]
*moving my ideas here*

`link`, `entangle`, `couple`, and `graft`.

I quite like `entangle` tbh as it fits the description well, but I can understand if you don't for it - it's quite long hah.

**Comment by TodePond** [comment]
I'm wondering if those ones also suggest that there's a two-way connection? I'm liking `follow` at the moment because it's clear that it's one-way 🤔

**Comment by Magnogen** [comment]
I imagined it like a trailer being linked to the main vehicle, the car does the driving and the trailer follows... oh hey wait yeah follow works.

**Comment by TodePond** [comment]
I'm gonna go with `subscribe` I think

**Comment by Magnogen** [comment]
To everyone who sees this issue in the future, SUBSCRIBE TO TODEPOND!
